# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDial,
    QGraphicsView, QGroupBox, QLCDNumber, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(741, 584)
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"background-image: url(/home/abdul/AbdulRehman_ws/src/thesis/Mapper/bckgnd_1.jpg)")
        self.actionOpen_Map = QAction(MainWindow)
        self.actionOpen_Map.setObjectName(u"actionOpen_Map")
        self.actionSave_Map = QAction(MainWindow)
        self.actionSave_Map.setObjectName(u"actionSave_Map")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo_Ctrl_Y = QAction(MainWindow)
        self.actionRedo_Ctrl_Y.setObjectName(u"actionRedo_Ctrl_Y")
        self.actionCut_Ctrl_X = QAction(MainWindow)
        self.actionCut_Ctrl_X.setObjectName(u"actionCut_Ctrl_X")
        self.actionCopy_Ctrl_C = QAction(MainWindow)
        self.actionCopy_Ctrl_C.setObjectName(u"actionCopy_Ctrl_C")
        self.actionPaste_Ctrl_V = QAction(MainWindow)
        self.actionPaste_Ctrl_V.setObjectName(u"actionPaste_Ctrl_V")
        self.actionInfo = QAction(MainWindow)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionTutorial = QAction(MainWindow)
        self.actionTutorial.setObjectName(u"actionTutorial")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 741, 541))
        font = QFont()
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.traj_btn = QPushButton(self.tab)
        self.traj_btn.setObjectName(u"traj_btn")
        self.traj_btn.setGeometry(QRect(290, 140, 111, 51))
        self.custom_btn_3 = QPushButton(self.tab)
        self.custom_btn_3.setObjectName(u"custom_btn_3")
        self.custom_btn_3.setGeometry(QRect(250, 450, 111, 51))
        self.logo_ias = QLabel(self.tab)
        self.logo_ias.setObjectName(u"logo_ias")
        self.logo_ias.setGeometry(QRect(630, 460, 84, 37))
        self.logo_ias.setAutoFillBackground(False)
        self.logo_ias.setStyleSheet(u"background-image: url(/home/abdul/AbdulRehman_ws/src/thesis/Mapper/IAS_logo_small.png)")
        self.logo_ias.setWordWrap(False)
        self.use_keyboard_chk = QCheckBox(self.tab)
        self.use_keyboard_chk.setObjectName(u"use_keyboard_chk")
        self.use_keyboard_chk.setGeometry(QRect(610, 420, 121, 21))
        self.custom_btn_1 = QPushButton(self.tab)
        self.custom_btn_1.setObjectName(u"custom_btn_1")
        self.custom_btn_1.setGeometry(QRect(10, 450, 111, 51))
        self.custom_btn_2 = QPushButton(self.tab)
        self.custom_btn_2.setObjectName(u"custom_btn_2")
        self.custom_btn_2.setGeometry(QRect(130, 450, 111, 51))
        self.speed_real = QLCDNumber(self.tab)
        self.speed_real.setObjectName(u"speed_real")
        self.speed_real.setGeometry(QRect(430, 140, 101, 31))
        self.custom_btn_4 = QPushButton(self.tab)
        self.custom_btn_4.setObjectName(u"custom_btn_4")
        self.custom_btn_4.setGeometry(QRect(370, 450, 111, 51))
        self.Foward = QPushButton(self.tab)
        self.Foward.setObjectName(u"Foward")
        self.Foward.setGeometry(QRect(540, 240, 91, 51))
        self.log_data_btn = QPushButton(self.tab)
        self.log_data_btn.setObjectName(u"log_data_btn")
        self.log_data_btn.setGeometry(QRect(10, 140, 111, 51))
        self.save_map_btn = QPushButton(self.tab)
        self.save_map_btn.setObjectName(u"save_map_btn")
        self.save_map_btn.setGeometry(QRect(150, 140, 111, 51))
        self.speed_dial = QDial(self.tab)
        self.speed_dial.setObjectName(u"speed_dial")
        self.speed_dial.setGeometry(QRect(450, 220, 81, 71))
        font1 = QFont()
        font1.setPointSize(11)
        self.speed_dial.setFont(font1)
        self.speed_dial.setAutoFillBackground(False)
        self.speed_dial.setMaximum(10)
        self.speed_dial.setSingleStep(1)
        self.speed_dial.setPageStep(10)
        self.speed_dial.setValue(0)
        self.speed_dial.setSliderPosition(0)
        self.speed_dial.setTracking(True)
        self.speed_dial.setOrientation(Qt.Horizontal)
        self.speed_dial.setWrapping(False)
        self.speed_dial.setNotchesVisible(True)
        self.Speed_3 = QLabel(self.tab)
        self.Speed_3.setObjectName(u"Speed_3")
        self.Speed_3.setEnabled(True)
        self.Speed_3.setGeometry(QRect(450, 280, 31, 21))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setItalic(True)
        font2.setKerning(True)
        self.Speed_3.setFont(font2)
        self.Speed_4 = QLabel(self.tab)
        self.Speed_4.setObjectName(u"Speed_4")
        self.Speed_4.setGeometry(QRect(500, 280, 31, 21))
        font3 = QFont()
        font3.setPointSize(9)
        font3.setItalic(True)
        self.Speed_4.setFont(font3)
        self.Backward = QPushButton(self.tab)
        self.Backward.setObjectName(u"Backward")
        self.Backward.setGeometry(QRect(540, 360, 91, 51))
        self.on_off_btn = QPushButton(self.tab)
        self.on_off_btn.setObjectName(u"on_off_btn")
        self.on_off_btn.setGeometry(QRect(10, 20, 111, 51))
        self.on_off_btn.setAutoFillBackground(False)
        self.Auto_map_chk = QCheckBox(self.tab)
        self.Auto_map_chk.setObjectName(u"Auto_map_chk")
        self.Auto_map_chk.setGeometry(QRect(420, 170, 111, 31))
        self.info_box = QTextEdit(self.tab)
        self.info_box.setObjectName(u"info_box")
        self.info_box.setGeometry(QRect(540, 20, 191, 211))
        font4 = QFont()
        font4.setItalic(False)
        self.info_box.setFont(font4)
        self.info_box.setAcceptDrops(True)
        self.info_box.setReadOnly(True)
        self.Right = QPushButton(self.tab)
        self.Right.setObjectName(u"Right")
        self.Right.setGeometry(QRect(640, 300, 91, 51))
        self.speed_lcd = QLCDNumber(self.tab)
        self.speed_lcd.setObjectName(u"speed_lcd")
        self.speed_lcd.setGeometry(QRect(430, 20, 101, 51))
        self.path_to_map = QLineEdit(self.tab)
        self.path_to_map.setObjectName(u"path_to_map")
        self.path_to_map.setGeometry(QRect(80, 90, 451, 31))
        self.Left = QPushButton(self.tab)
        self.Left.setObjectName(u"Left")
        self.Left.setGeometry(QRect(440, 300, 91, 51))
        self.start_rob_btn = QPushButton(self.tab)
        self.start_rob_btn.setObjectName(u"start_rob_btn")
        self.start_rob_btn.setGeometry(QRect(150, 20, 111, 51))
        self.Break = QPushButton(self.tab)
        self.Break.setObjectName(u"Break")
        self.Break.setGeometry(QRect(540, 300, 91, 51))
        self.Speed_2 = QLabel(self.tab)
        self.Speed_2.setObjectName(u"Speed_2")
        self.Speed_2.setGeometry(QRect(10, 100, 71, 21))
        self.map_display = QGraphicsView(self.tab)
        self.map_display.setObjectName(u"map_display")
        self.map_display.setGeometry(QRect(10, 210, 421, 231))
        self.gen_map_btn = QPushButton(self.tab)
        self.gen_map_btn.setObjectName(u"gen_map_btn")
        self.gen_map_btn.setGeometry(QRect(290, 20, 111, 51))
        self.custom_btn_5 = QPushButton(self.tab)
        self.custom_btn_5.setObjectName(u"custom_btn_5")
        self.custom_btn_5.setGeometry(QRect(490, 450, 111, 51))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 641, 241))
        self.Train = QPushButton(self.groupBox)
        self.Train.setObjectName(u"Train")
        self.Train.setGeometry(QRect(10, 30, 161, 91))
        self.Test_btn = QPushButton(self.groupBox)
        self.Test_btn.setObjectName(u"Test_btn")
        self.Test_btn.setGeometry(QRect(190, 30, 151, 91))
        self.stop_train_test = QPushButton(self.groupBox)
        self.stop_train_test.setObjectName(u"stop_train_test")
        self.stop_train_test.setGeometry(QRect(360, 30, 151, 91))
        self.Control_btn = QPushButton(self.groupBox)
        self.Control_btn.setObjectName(u"Control_btn")
        self.Control_btn.setGeometry(QRect(10, 150, 161, 81))
        self.virtual_obj_btn = QPushButton(self.groupBox)
        self.virtual_obj_btn.setObjectName(u"virtual_obj_btn")
        self.virtual_obj_btn.setGeometry(QRect(190, 150, 151, 81))
        self.close_window_btn = QPushButton(self.groupBox)
        self.close_window_btn.setObjectName(u"close_window_btn")
        self.close_window_btn.setGeometry(QRect(360, 150, 151, 81))
        self.shape_selector = QComboBox(self.groupBox)
        self.shape_selector.setObjectName(u"shape_selector")
        self.shape_selector.setGeometry(QRect(520, 150, 111, 25))
        self.rl_type_selector = QComboBox(self.groupBox)
        self.rl_type_selector.setObjectName(u"rl_type_selector")
        self.rl_type_selector.setGeometry(QRect(520, 30, 111, 25))
        self.groupBox_2 = QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 260, 641, 241))
        self.groupBox_2.setAutoFillBackground(False)
        self.ML_custom = QPushButton(self.groupBox_2)
        self.ML_custom.setObjectName(u"ML_custom")
        self.ML_custom.setGeometry(QRect(10, 30, 161, 91))
        self.ML_2 = QPushButton(self.groupBox_2)
        self.ML_2.setObjectName(u"ML_2")
        self.ML_2.setGeometry(QRect(190, 30, 151, 91))
        self.ML_3 = QPushButton(self.groupBox_2)
        self.ML_3.setObjectName(u"ML_3")
        self.ML_3.setGeometry(QRect(360, 30, 151, 91))
        self.ML_4 = QPushButton(self.groupBox_2)
        self.ML_4.setObjectName(u"ML_4")
        self.ML_4.setGeometry(QRect(10, 150, 161, 81))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.checkBox = QCheckBox(self.tab_4)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(340, 70, 121, 23))
        self.checkBox_2 = QCheckBox(self.tab_4)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(340, 90, 71, 23))
        self.custom_ml = QPushButton(self.tab_4)
        self.custom_ml.setObjectName(u"custom_ml")
        self.custom_ml.setGeometry(QRect(80, 70, 131, 51))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 741, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen_Map)
        self.menuFile.addAction(self.actionSave_Map)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo_Ctrl_Y)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut_Ctrl_X)
        self.menuEdit.addAction(self.actionCopy_Ctrl_C)
        self.menuEdit.addAction(self.actionPaste_Ctrl_V)
        self.menuHelp.addAction(self.actionInfo)
        self.menuHelp.addAction(self.actionTutorial)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen_Map.setText(QCoreApplication.translate("MainWindow", u"Open Map", None))
#if QT_CONFIG(shortcut)
        self.actionOpen_Map.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_Map.setText(QCoreApplication.translate("MainWindow", u"Save Map", None))
#if QT_CONFIG(shortcut)
        self.actionSave_Map.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo    Ctrl+Z", None))
        self.actionRedo_Ctrl_Y.setText(QCoreApplication.translate("MainWindow", u"Redo    Ctrl+Y", None))
        self.actionCut_Ctrl_X.setText(QCoreApplication.translate("MainWindow", u"Cut       Ctrl+X", None))
        self.actionCopy_Ctrl_C.setText(QCoreApplication.translate("MainWindow", u"Copy    Ctrl+C", None))
        self.actionPaste_Ctrl_V.setText(QCoreApplication.translate("MainWindow", u"Paste   Ctrl+V", None))
        self.actionInfo.setText(QCoreApplication.translate("MainWindow", u"Info", None))
        self.actionTutorial.setText(QCoreApplication.translate("MainWindow", u"Tutorial", None))
        self.traj_btn.setText(QCoreApplication.translate("MainWindow", u"Trajectory", None))
        self.custom_btn_3.setText(QCoreApplication.translate("MainWindow", u"Custom 3", None))
        self.logo_ias.setText("")
        self.use_keyboard_chk.setText(QCoreApplication.translate("MainWindow", u"Use Keyboard", None))
        self.custom_btn_1.setText(QCoreApplication.translate("MainWindow", u"Custom 1", None))
        self.custom_btn_2.setText(QCoreApplication.translate("MainWindow", u"Custom 2", None))
        self.custom_btn_4.setText(QCoreApplication.translate("MainWindow", u"Custom 4", None))
        self.Foward.setText(QCoreApplication.translate("MainWindow", u"Forward(w)", None))
        self.log_data_btn.setText(QCoreApplication.translate("MainWindow", u"Log Data", None))
        self.save_map_btn.setText(QCoreApplication.translate("MainWindow", u"Save Map", None))
        self.Speed_3.setText(QCoreApplication.translate("MainWindow", u"0.01", None))
        self.Speed_4.setText(QCoreApplication.translate("MainWindow", u"0.15", None))
        self.Backward.setText(QCoreApplication.translate("MainWindow", u"Backward(s)", None))
        self.on_off_btn.setText(QCoreApplication.translate("MainWindow", u"ON/OFF", None))
        self.Auto_map_chk.setText(QCoreApplication.translate("MainWindow", u"Auto Map ", None))
        self.Right.setText(QCoreApplication.translate("MainWindow", u"Right(d)", None))
        self.Left.setText(QCoreApplication.translate("MainWindow", u"Left(a)", None))
        self.start_rob_btn.setText(QCoreApplication.translate("MainWindow", u"Start Robot", None))
        self.Break.setText(QCoreApplication.translate("MainWindow", u"Stop(x)", None))
        self.Speed_2.setText(QCoreApplication.translate("MainWindow", u"Map Path", None))
        self.gen_map_btn.setText(QCoreApplication.translate("MainWindow", u"Generate Map", None))
        self.custom_btn_5.setText(QCoreApplication.translate("MainWindow", u"Custom 5", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Mapper", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Reinforcment Learning", None))
        self.Train.setText(QCoreApplication.translate("MainWindow", u"Train", None))
        self.Test_btn.setText(QCoreApplication.translate("MainWindow", u"Test", None))
        self.stop_train_test.setText(QCoreApplication.translate("MainWindow", u"Stop RL", None))
        self.Control_btn.setText(QCoreApplication.translate("MainWindow", u"Control", None))
        self.virtual_obj_btn.setText(QCoreApplication.translate("MainWindow", u"Virtual Objects", None))
        self.close_window_btn.setText(QCoreApplication.translate("MainWindow", u"Close Windows", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Machine Learning", None))
        self.ML_custom.setText(QCoreApplication.translate("MainWindow", u"Train", None))
        self.ML_2.setText(QCoreApplication.translate("MainWindow", u"Test", None))
        self.ML_3.setText(QCoreApplication.translate("MainWindow", u"Auto Label", None))
        self.ML_4.setText(QCoreApplication.translate("MainWindow", u"Risk", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Localization Adversary", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Object Adversary", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Localization", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"Object", None))
        self.custom_ml.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"ML Control", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Monitored space localization", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Monitored space object", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

